<?xml version="1.0"?>
<robot name="dyn_ef_robot" 
  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find dynamic_end_effector)/urdf/dynamic-ef.gazebo" />

  <!-- RViz-only colors -->
  <material name="red">
    <color rgba="1.0 0 0 1.0"/>
  </material>
  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>

  <!-- some properties for the urdf file -->
  <xacro:property name="height" value="0.0" />
  <xacro:property name="camera_link_size" value="0.01" /> <!-- Size of square 'camera' box -->

  <!-- inertias for all links -->
  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>

  <!-- interface between moveit and real robot controllers -->
  <xacro:macro name="transmission_block" params="joint_name">
    <transmission name="trans_${joint_name}">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${joint_name}">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="motor_${joint_name}">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>


  <!--  ##################### start listing links and joints  ##############################  -->
  <link name="world"/>

  <joint name="fixy" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0.09" rpy="${pi/2.0} 0 0" />
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/h54-200-s500-r.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0.09" rpy="${pi/2.0} 0 0" />
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/h54-200-s500-r_simple.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="0.8"/>
  </link>


  <joint name="base_link_to_base_yaw_link_joint" type="revolute">
    <!-- <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="${-2.0}" soft_upper_limit="${2.0}"/> -->
    <parent link="base_link"/>
    <child link="base_yaw_link"/>
    <origin xyz="0 0 0.126" rpy="0 0 0" />
    <axis xyz="0 0 1"/>
    <dynamics damping="1.0" friction="5.0"/>
    <limit upper="${2.0}" lower="${-2.0}" effort="45" velocity="5"/>
  </joint>

  <xacro:transmission_block joint_name="base_link_to_base_yaw_link_joint"/>

  <link name="base_yaw_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 ${-pi} 0" />
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/assembly_link2.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 ${-pi} 0" />
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/assembly_link2_simple.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="10"/>
      <inertia ixx="0.01" ixy="0.01" ixz="0.01" iyy="0.01" iyz="0.01" izz="0.01"/>
    </inertial>
    <xacro:default_inertial mass="0.8"/>
  </link>

  <joint name="base_yaw_link_to_first_link_joint" type="revolute">
    <!-- <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-2.0" soft_upper_limit="2.0"/> -->
    <parent link="base_yaw_link"/>
    <child link="first_link"/>
    <origin xyz="0 0 0.0392"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="1.0" friction="1.0"/>
    <limit upper="2.0" lower="-2.0" effort="45" velocity="5"/>
  </joint>

  <xacro:transmission_block joint_name="base_yaw_link_to_first_link_joint"/>

  <link name="first_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${-pi/2}" />
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/assembly_arm_1.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 ${-pi/2}" />
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/assembly_arm_1_simple.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="2"/>
  </link>

  <joint name="first_link_to_second_link_joint" type="revolute">
    <!-- <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="${-pi/4}" soft_upper_limit="${pi}"/> -->
    <parent link="first_link"/>
    <child link="second_link"/>
    <origin xyz="0.034613 0.00625 0.457247"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="1.0" friction="5.0"/>
    <limit lower="${-pi/4}" upper="${pi}" effort="45" velocity="5"/>
  </joint>

  <xacro:transmission_block joint_name="first_link_to_second_link_joint"/>

  <link name="second_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${pi/2}" />
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/assembly_arm_2.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 ${pi/2}" />
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/assembly_arm_2_simple.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="1"/>
  </link>

  <joint name="second_link_to_third_link_joint" type="revolute">
    <!-- <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="${-pi/2}" soft_upper_limit="${3*pi/2}"/> -->
    <parent link="second_link"/>
    <child link="third_link"/>
    <origin xyz="-0.031 -0.001 0.422"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="1.0" friction="5.0"/>
    <limit upper="${3*pi/2}" lower="${-pi/2}" effort="45" velocity="5"/>
  </joint>

  <xacro:transmission_block joint_name="second_link_to_third_link_joint"/>

  <link name="third_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/frame_mx108.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/frame_mx108_simple.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="0.1"/>
  </link>

  <joint name="third_link_to_fourth_link_joint" type="revolute">
    <!-- <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-1.8" soft_upper_limit="1.8"/> -->
    <parent link="third_link"/>
    <child link="fourth_link"/>
    <origin xyz="0 0 0.037"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="1.0" friction="5.0"/>
    <limit upper="1.8" lower="-1.8" effort="45" velocity="5"/>
  </joint>

  <xacro:transmission_block joint_name="third_link_to_fourth_link_joint"/>

  <link name="fourth_link">
    <visual>
      <origin xyz="0 0 0" rpy="${-pi/2} 0 ${pi/2}" />
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/assembly_hand.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${-pi/2} 0 ${pi/2}" />
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/assembly_hand_simple.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="0.3"/>
  </link>

  <joint name="fourth_link_to_fifth_link_joint" type="revolute">
    <!-- <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="${-pi}" soft_upper_limit="${pi}"/> -->
    <parent link="fourth_link"/>
    <child link="fifth_link"/>
    <origin xyz="0 0.0005 0.1233"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="1.0" friction="5.0"/>
    <limit upper="${pi*2}" lower="${-pi*2}" effort="45" velocity="5"/>
  </joint>

  <xacro:transmission_block joint_name="fourth_link_to_fifth_link_joint"/>


  <link name="fifth_link">
    <visual>
      <origin xyz="0.004143 -0.006953 0.004" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/Pointing_Finger2.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.004143 -0.006953 0.004" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/Pointing_Finger2_simple.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="0.01"/>
  </link>

  <!-- fixed camera joint -->
  <joint name="camera_joint" type="fixed">
    <!-- <axis xyz="0 1 0" /> -->
    <origin xyz="0 0.041 ${camera_link_size/2 + 0.099666}" rpy="0 ${-pi/2} ${-pi/2}"/>
    <parent link="fourth_link"/>
    <child link="camera_link"/>
  </joint>

  <!-- Camera -->
  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_link_size} ${camera_link_size} ${camera_link_size}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_link_size} ${camera_link_size} ${camera_link_size}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>



</robot>