<?xml version="1.0"?>
<robot name="dyn_ef_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/dyn_ef_robot</robotNamespace>
    </plugin>
  </gazebo>

  <material name="red">
    <color rgba="1.0 0 0 1.0"/>
  </material>

  <xacro:property name="height" value="0.0" />
  <xacro:property name="camera_link_size" value="0.05" /> <!-- Size of square 'camera' box -->
  
  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="transmission_block" params="joint_name">
    <transmission name="trans_${joint_name}">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${joint_name}">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="motor_${joint_name}">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>


  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>

  <!--                                start listing links and joints                                                -->
  <link name="world"/>

  <joint name="fixy" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0.09" rpy="${pi/2.0} 0 0" />
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/h54-200-s500-r.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0.09" rpy="${pi/2.0} 0 0" />
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/h54-200-s500-r.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="0.8"/>
  </link>


  <joint name="base_link_to_base_yaw_link_joint" type="revolute">
    <parent link="base_link"/>
    <child link="base_yaw_link"/>
    <origin xyz="0 0 0.126"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="1.0" friction="5.0"/>
    <limit upper="${pi}" lower="${-pi}" effort="45" velocity="1"/>
  </joint>
  
  <xacro:transmission_block joint_name="base_link_to_base_yaw_link_joint"/>

  <link name="base_yaw_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/assembly_base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/assembly_base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="10"/>
      <inertia ixx="0.01" ixy="0.01" ixz="0.01" iyy="0.01" iyz="0.01" izz="0.01"/>
    </inertial>
    <xacro:default_inertial mass="0.8"/>
  </link>

  <joint name="base_yaw_link_to_first_link_joint" type="revolute">
    <parent link="base_yaw_link"/>
    <child link="first_link"/>
    <origin xyz="0 0 0.042"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="1.0" friction="1.0"/>
    <limit upper="2.0" lower="-2.0" effort="45" velocity="1"/>
  </joint>

  <xacro:transmission_block joint_name="base_yaw_link_to_first_link_joint"/>

  <link name="first_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2.0} 0 0" />
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/assembly_linkOne.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2.0} 0 0" />
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/assembly_linkOne.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="2"/>
  </link>

  <joint name="first_link_to_second_link_joint" type="revolute">
    <parent link="first_link"/>
    <child link="second_link"/>
    <origin xyz="0 0 0.806"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="1.0" friction="5.0"/>
    <limit upper="${0.9*pi}" lower="${-0.9*pi}" effort="45" velocity="1"/>
  </joint>

  <xacro:transmission_block joint_name="first_link_to_second_link_joint"/>

  <link name="second_link">
    <visual>
      <origin xyz="-0.033 0 0" rpy="${pi/2.0} -${pi/2.0} 0" />
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/assembly_linkTwo.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="-0.033 0 0" rpy="${pi/2.0} -${pi/2.0} 0" />
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/assembly_linkTwo.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="1"/>
  </link>

  <joint name="second_link_to_third_link_joint" type="continuous">
    <parent link="second_link"/>
    <child link="third_link"/>
    <origin xyz="-0.06 0 0.61555"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="1.0" friction="5.0"/>
    <limit upper="${pi}" lower="${-pi}" effort="45" velocity="1"/>
  </joint>

  <xacro:transmission_block joint_name="second_link_to_third_link_joint"/>

  <link name="third_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/assembly_linkThree.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/assembly_linkThree.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="0.1"/>
  </link>

  <joint name="third_link_to_fourth_link_joint" type="continuous">
    <parent link="third_link"/>
    <child link="fourth_link"/>
    <origin xyz="-0.025262 0 0.0383"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="1.0" friction="5.0"/>
    <limit upper="2.0" lower="-2.0" effort="45" velocity="1"/>
  </joint>

  <xacro:transmission_block joint_name="third_link_to_fourth_link_joint"/>

  <link name="fourth_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2.0} 0 ${pi/2.0}" />
      <!-- <origin xyz="0 0 0" rpy="0 0 0"/> -->
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/assembly_linkFour.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2.0} 0 ${pi/2.0}" />
      <!-- <origin xyz="0 0 0" rpy="0 0 0"/> -->
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/assembly_linkFour.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="0.3"/>
  </link>

  <joint name="fourth_link_to_fifth_link_joint" type="revolute">
    <parent link="fourth_link"/>
    <child link="fifth_link"/>
    <origin xyz="0.0278 0 0.09375"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="1.0" friction="5.0"/>
    <limit upper="${pi}" lower="${-pi}" effort="45" velocity="1"/>
  </joint>

  <xacro:transmission_block joint_name="fourth_link_to_fifth_link_joint"/>


  <link name="fifth_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2.0} 0 0" />
      <!-- <origin xyz="0 0 0" rpy="0 0 0"/> -->
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/assembly_linkFive.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2.0} 0 0" />
      <!-- <origin xyz="0 0 0" rpy="0 0 0"/> -->
      <geometry>
        <mesh filename="package://dynamic_end_effector/meshes/assembly_linkFive.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="0.01"/>
  </link>

  <joint name="camera_joint" type="fixed">
    <!-- <axis xyz="0 1 0" /> -->
    <origin xyz="0 0 ${camera_link_size/2 + 0.01}" rpy="0 0 0"/>
    <parent link="fifth_link"/>
    <child link="camera_link"/>
  </joint>

  <!-- Camera -->
  <link name="camera_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_link_size} ${camera_link_size} ${camera_link_size}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_link_size} ${camera_link_size} ${camera_link_size}"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <!-- <gazebo reference="camera_link">  
 
  </gazebo> -->

    <!-- camera -->
  <gazebo reference="camera_link">
    <visual>  
      <material>  
        <ambient>0.70 0.19225 0.19225 1.0</ambient>  
        <diffuse>0.90 0.50754 0.50754 1.0</diffuse>  
        <specular>0.90 0.508273 0.508273 1.0</specular>  
        <emissive>0.0 0.0 0.0 0.0</emissive>  
      </material>  
    </visual> 
    <sensor type="camera" name="camera1">
      <update_rate>30.0</update_rate>
      <camera name="head">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>800</width>
          <height>800</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>0.0</updateRate>
        <cameraName>dyn_ef_robot/camera1</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>camera_link</frameName>
        <hackBaseline>0.07</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </plugin>
    </sensor>
  </gazebo>



</robot>