dyn_ef_robot:
# Publish all joint states --------------------------------------
  joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

# Position Controllers:
  joint1_controller:
    type: position_controllers/JointPositionController
    joint: base_link_to_base_yaw_link_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_controller:
    type: position_controllers/JointPositionController
    joint: base_yaw_link_to_first_link_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint3_controller:
    type: position_controllers/JointPositionController
    joint: first_link_to_second_link_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint4_controller:
    type: position_controllers/JointPositionController
    joint: second_link_to_third_link_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint5_controller:
    type: position_controllers/JointPositionController
    joint: third_link_to_fourth_link_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint6_controller:
    type: position_controllers/JointPositionController
    joint: fourth_link_to_fifth_link_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  